title: Home
resources:
  - url: /local/bignumber-card.js?v=1
    type: js
views:
  - title: Home
    icon: mdi:home-modern
    panel: true
    cards:

      - type: horizontal-stack
        cards:
          - type: sensor
            hours_to_show: 3
            graph: line
            detail: 2 # 6 points per hour
            entity: sensor.samjin_btn_1_temp
            name: Office
          - type: sensor
            hours_to_show: 3
            graph: line
            detail: 2
            entity: sensor.samjin_btn_2_temp
            name: Kitchen
          - type: sensor
            hours_to_show: 3
            graph: line
            detail: 2
            entity: sensor.samjin_btn_3_temp
            name: Bedroom
          - type: sensor
            hours_to_show: 3
            graph: line
            detail: 2
            entity: sensor.samjin_btn_4_temp
            name: Living Room


      - type: history-graph
        hours_to_show: 24
        refresh_interval: 300
        title: Apartment Temperatures
        entities:
          - entity: sensor.samjin_btn_1_temp
            name: Office
          - entity: sensor.samjin_btn_2_temp
            name: Kitchen
          - entity: sensor.samjin_btn_3_temp
            name: Bedroom
          - entity: sensor.samjin_btn_4_temp
            name: Living Room

      # Switches
      - type: entities
        title: Switches
        entities:
          - entity: light.cree_livingroom_lamp
            icon: mdi:lightbulb
            secondary_info: last-changed
          - entity: light.tr_livingroom_lamp
            icon: mdi:lightbulb
            secondary_info: last-changed
          - entity: light.tr_bedroom_lamp
            icon: mdi:lightbulb
            secondary_info: last-changed
          - entity: light.cree_bedroom_lamp
            icon: mdi:lightbulb
            secondary_info: last-changed
          - entity: switch.tr_kitchen_range_switch
            icon: mdi:lightbulb
            secondary_info: last-changed
          - entity: switch.tr_kitchen_sink_switch
            icon: mdi:lightbulb
            secondary_info: last-changed
          - entity: switch.tr_dining_room_switch
            icon: mdi:lightbulb
            secondary_info: last-changed
          - entity: switch.tr_livingroom_switch
            icon: mdi:lightbulb
            secondary_info: last-changed

      # Presense
      - type: entities
        title: Family
        show_header_toggle: false
        entities:
          - entity: person.eric
            secondary_info: last-changed
          - entity: person.heath
            secondary_info: last-changed


  # 3d Printer
  - title: OctoPrint
    icon: mdi:printer-3d
    cards:

      # Printer Controls/Camera
      - type: vertical-stack
        cards:
        - type: picture-entity
          name: Ender 3 Cam
          entity: camera.ender_3
          show_state: false
          tap_action: more-info
        - type: custom:bignumber-card
          title: Current Job Completion Status
          entity: sensor.ender3_job_percentage
          scale: 30px
          from: left
          min: 0
          max: 100
          severity:
            - value: 20
              style: 'var(--label-badge-red)'
            - value: 40
              style: 'var(--label-badge-yellow)'
            - value: 70
              style: 'var(--label-badge-green)'
        - type: glance
          show_header_toggle: false
          column_width: calc(100% / 3)
          entities:
            - entity: binary_sensor.ender3_printing
              name: Printing Status
              icon: mdi:printer-wireless
            - entity: binary_sensor.ender3_printing_error
              name:  Error State
              icon: mdi:printer-alert
            - entity: sensor.ender3_current_state
              name: Current Status

      - type: vertical-stack
        cards:
        - type: horizontal-stack
          cards:
            - type: gauge
              name: Bed Temp
              entity: sensor.ender3_actual_bed_temp
              unit_of_measurement: 째C
              min: 0
              max: 150
              severity:
                red: 120
                amber: 0
                green: 60
              #scale: '50px'
            - type: gauge
              name: Hot End Temp
              entity: sensor.ender3_actual_tool0_temp
              unit_of_measurement: 째C
              min: 0
              max: 260
              severity:
                red: 225
                amber: 0
                green: 200
              #scale: '50px'
        - type: horizontal-stack
          cards:
            - type: gauge
              name: Bed Target
              entity: sensor.ender3_target_bed_temp
              unit_of_measurement: 째C
              min: 0
              max: 150
              severity:
                red: 120
                amber: 0
                green: 59
              #scale: '50px'

            - type: gauge
              name: Hot End Target
              entity: sensor.ender3_target_tool0_temp
              unit_of_measurement: 째C
              min: 0
              max: 260
              severity:
                red: 225
                amber: 0
                green: 199
              #scale: '50px'
        - type: horizontal-stack
          cards:
            - type: sensor
              name: Elapsed
              entity: sensor.ender3_time_elapsed
              graph: none

            - type: sensor
              name: Remaining
              entity: sensor.ender3_time_remaining
              graph: none
