# The Cloud
  google_actions:
    filter:
      include_domains:
        - zha
        - light
        - switch

    entity_config:

      # Switches
      switch.tr_kitchen_range_switch:
        name: Kitchen Range Light Switch
        aliases:
          - range light
          - counter light
        room: kitchen
      switch.tr_kitchen_sink_switch:
        name: Kitchen Sink Light Switch
        aliases:
          - sink light
          - island light
        room: kitchen
      switch.tr_entryway_kitchen_switch:
        name: Entryway Light (in Kitchen) Switch
        aliases:
          - entryway light
          - door light
        room: kitchen
      switch.tr_dining_room_switch:
        name: Dining Room Switch
        room: dining room

      # lights
      light.tr_livingroom_lamp:
        name: Livingroom Lamp
        aliases:
          - couch lamp
          - livingroom lamp
        room: livingroom
      light.tr_bedroom_lamp:
        name: Bedroom Lamp
        aliases:
          - bedside lamp
          - bedroom light
        room: master bedroom