# The Cloud
  google_actions:
    filter:
      include_domains:
        - zha
        - light
        - switch

    entity_config:

      # Switches
      # Kitchen
      switch.tr_kitchen_range_switch:
        name: Counter Light
        aliases:
          - Range Light
          - Fridge Light
          - Cabinet Light
        room: kitchen

      switch.tr_kitchen_sink_switch:
        name: Sink Light
        aliases:
          - Island Light
        room: kitchen

      # Entryway
      switch.tr_entryway_kitchen_switch:
        name: Entryway Light
        aliases:
          - Door Light
        room: entryway

      # Dining Room
      switch.tr_dining_room_switch:
        name: Dining Room Light
        room: dining room
          - Pantry Light

      # lights
      # Living Room
      light.tr_livingroom_lamp:
        name: Couch Table Light
        aliases:
          - end table light
          - end table lamp
          - table lamp
          - table light
        room: livingroom

      light.cree_livingroom_lamp:
        name: Couch Light
        aliases:
          - couch lamp
          - couch floor lamp
        room: livingroom

      # Master Bedroom
      light.tr_bedroom_lamp:
        name: Nightstand Light
        aliases:
          - bedside lamp
          - nightstand lamp
        room: master bedroom

      light.tr_bedroom_lamp:
        name: Bedroom Light
        aliases:
          - bedroom lamp
        room: master bedroom
