# The Cloud
  google_actions:
    filter:
      include_domains:
        - zha
        - light
        - switch
        - group

    entity_config:

      # Switches
      # Kitchen
      switch.tr_kitchen_range_switch:
        name: Counter Light
        room: kitchen
        aliases:
          - Range Light
          - Fridge Light
          - Cabinet Light

      switch.tr_kitchen_sink_switch:
        name: Sink Light
        room: kitchen
        aliases:
          - Island Light

      # Entryway
      switch.tr_livingroom_switch:
        name: Living Room Light
        room: Living Room

      # Dining Room
      switch.tr_dining_room_switch:
        name: Dining Room Light
        room: dining room
        aliases:
          - Pantry Light

      # lights
      # Living Room
      light.tr_livingroom_lamp:
        name: Table Light
        room: Living Room
        aliases:
          - end table light
          - end table lamp
          - table lamp
          - table light

      light.cree_livingroom_lamp:
        name: Couch Light
        room: Living Room
        aliases:
          - couch lamp
          - couch floor lamp

      # Master Bedroom
      light.tr_bedroom_lamp:
        name: Nightstand Light
        room: master bedroom
        aliases:
          - bedside lamp
          - nightstand lamp

      light.cree_bedroom_lamp:
        name: Bedroom Light
        room: master bedroom
        aliases:
          - bedroom lamp
