# Presence Detection
  - platform: bluetooth_tracker
    consider_home: 300
    new_device_defaults:
      track_new_devices: false
  - platform: nmap_tracker  
    hosts: 192.168.1.0/24
    interval_seconds: 30
    home_interval: 5
    consider_home: 300
    new_device_defaults:
      track_new_devices: false